### ISSUE TITLE
Nonce not set

### ISSUE THREAD

**Issue by theKidOfArcrania** [tsg-ut/ctfd-theme-tsgctf#9]
Hi, nice theme.

I'm having issues with getting the nonce to be properly passed into the theme (i.e. when you need to use it to login into CTFd). Im currently using the dist branch, and it looks like the login.html template file is referencing some `nonce` variable, passing it as a meta tag, (see [this](https://github.com/tsg-ut/ctfd-theme-tsgctf/blob/dist/templates/login.html)). 

If I cross-referenced it to the [login.html template file of core theme](https://github.com/CTFd/CTFd/blob/master/CTFd/themes/core/templates/login.html), it shows that it is obtaining the nonce from `form.nonce()`, where `form = Forms.auth.LoginForm()`. 

Was there a reason for this difference, and did you guys patch anywhere else in CTFd, to make sure the nonce variable was properly passed from the `render_template` function calls in python?

P.S. when I try to login/register using this theme, it will mysteriously fail with 403, because the csrf token is empty string.

UPDATE: I think this looks like it's due to an [old version of CTFd](https://github.com/CTFd/CTFd/blob/dcfa02877dc17475e8c09c71a5de407b1e7affea/CTFd/themes/core/templates/login.html) referring to a 2.x.y version I think it uses the nonce variable instead.

**Comment by hakatashi** [comment]
Yes, this was due to the breaking change in CTFd v3.

I will fix it when I have time, or when we are hosting next TSG CTF 🙃

ty for using our theme anyway!
